application: school-attendance
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/images/school-bell-favicon.ico
  upload: static/images/school-bell-favicon.ico

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  
- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /.*
  script: main.py
  login: required

builtins:
- remote_api: on

