application: school-attendance-dev
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /favicon.ico
  static_files: static/images/school-bell-favicon.ico
  upload: static/images/school-bell-favicon.ico

- url: /apple-touch-icon.png
  static_files: static/images/school-bell-favicon.ico
  upload: static/images/school-bell-favicon.ico

- url: /attendance.css
  static_files: static/css/attendance.css
  upload: static/css/attendance.css

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  
- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /load/.*
  script: load_data.app
  login: admin

- url: /attend
  script: attend.app
  login: required

- url: /.*
  script: main.app
  login: required

builtins:
- remote_api: on

