application: s~school-attendance
version: 28p
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /_ah/spi/.*
  script: attendance_api.application

- url: /favicon.ico
  static_files: static/images/school-bell-favicon.ico
  upload: static/images/school-bell-favicon.ico

- url: /apple-touch-icon.png
  static_files: static/images/school-bell-favicon.ico
  upload: static/images/school-bell-favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /html
  static_dir: static/html

- url: /attendance.css
  static_files: static/css/attendance.css
  upload: static/css/attendance.css

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  
- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /load/.*
  script: load_data.app
  login: admin

- url: /attend
  script: attend.app
  login: required

- url: /.*
  script: main.app
  login: required

builtins:
- remote_api: on

libraries:
- name: endpoints
  version: 1.0